Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2023-07, with the labels that each got.

#12 fix: quicksight check in china region
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#17 fix: allow change the interval of data processing when editing pipeline
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: bug

#23 feat(api): add file type validation for uploading plug-ins
  src/control-plane/backend/lambda/api/common/constants.ts
  src/control-plane/backend/lambda/api/common/request-valid.ts
  src/control-plane/backend/lambda/api/router/plugin.ts
  src/control-plane/backend/lambda/api/test/api/plugin.test.ts
Labels: security

#35 fix: use stack parameter instead of fixed pattern as principal value …
  frontend/src/pages/pipelines/create/CreatePipeline.tsx
  frontend/src/pages/pipelines/create/steps/Reporting.tsx
  frontend/src/ts/init.ts
  frontend/src/types/pipeline.d.ts
  src/common/constant.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
  src/data-reporting-quicksight-stack.ts
  src/reporting/lambda/custom-resource/quicksight/index.ts
  src/reporting/parameter.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#39 fix: enable rollback when update & upgrade pipeline with tags
  src/control-plane/backend/lambda/api/common/stack-params-valid.ts
  src/control-plane/backend/lambda/api/common/types.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
  src/control-plane/backend/lambda/sfn-action/index.ts
Labels: bug, Cherry Pick

#37 fix: create function for get identity region from error message
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/test/api/env.test.ts
Labels: bug

#40 fix: replace api function resource id
  src/control-plane/backend/click-stream-api.ts
  test/control-plane/alb-control-plane-stack.test.ts
  test/control-plane/click-stream-api.test.ts
  test/control-plane/cloudfront-control-plane-stack.test.ts
Labels: webconsole-backend

#43 chore: restrict iam permissions
  src/control-plane/backend/stack-action-state-machine-construct.ts
  test/control-plane/click-stream-api.test.ts
Labels: security

#54 fix: edit pipeline not allow data processing cron or rate expression
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: Cherry Pick

#63 chore: set 'compression' as default true for SDK configurations
  frontend/src/ts/guideConst.ts
Labels: bug, webconsole-frontend

#65 chore: set 'compression' as default true for SDK configurations
  frontend/src/ts/guideConst.ts
Labels: Cherry Pick, v1.0.x

#51 fix: delete CompatibleArchitectures for lambda layer
  src/control-plane/backend/layer/lambda-web-adapter/layer.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#62 fix: plugin description display error
  frontend/public/locales/en/plugin.json
  frontend/public/locales/zh/plugin.json
  frontend/src/pages/plugins/comps/PluginTable.tsx
  src/control-plane/backend/config/dictionary.json
Labels: bug, webconsole-frontend

#68 fix: increase the execution timeout of the state machine
  src/control-plane/backend/stack-action-state-machine-construct.ts
  src/control-plane/backend/stack-workflow-state-machine-construct.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug, v1.0.x

#70 fix: retry the failed stacks
  src/control-plane/backend/lambda/sfn-action/index.ts
  test/control-plane/lambda/sfn-action.test.ts
Labels: bug, v1.0.x

#73 fix: apply time filter for the visuals of device report
  src/reporting/private/template-def.json
Labels: bug, v1.0.x

#78 chore: delete bad url in top navigation
  frontend/src/components/layouts/Header.tsx
Labels: webconsole-frontend

#80 fix: increase the execution timeout of the state machine
  src/control-plane/backend/stack-action-state-machine-construct.ts
  src/control-plane/backend/stack-workflow-state-machine-construct.ts
  test/control-plane/click-stream-api.test.ts
Labels: Cherry Pick

#82 fix: delete broken and duplicated links in top navigation
  frontend/src/components/layouts/Header.tsx
Labels: Cherry Pick

#81 fix: retry the failed stacks
  src/control-plane/backend/lambda/sfn-action/index.ts
  test/control-plane/lambda/sfn-action.test.ts
Labels: Cherry Pick

#100 chore: copy extensions asset from lambda-adapter image
  src/control-plane/backend/layer/lambda-web-adapter/Dockerfile
  src/control-plane/backend/layer/lambda-web-adapter/bootstrap
Labels: webconsole-backend
