Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2023-10, with the labels that each got.

#282 fix: insufficient permission when creating ingestion server without einsufficient permission when creating ingestion server without existing service link role of AGA #259
  src/control-plane/backend/stack-action-state-machine-construct.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#291 chore: optimize pseudorandom in create-schema
  src/analytics/lambdas/custom-resource/create-schemas.ts
  src/common/alb.ts
  src/common/cfn-nag.ts
  src/common/utils.ts
  src/control-plane/auth/authorizer.ts
  src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
  src/control-plane/backend/lambda/api/middle-ware/auth-role.ts
  test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
Labels: engineering-excellence

#334 docs: add user identifier in SDK manual
  docs/en/sdk-manual/user-identifier.md
  docs/mkdocs.en.yml
  docs/mkdocs.zh.yml
  docs/zh/sdk-manual/user-identifier.md
Labels: documentation

#365 fix: admin user custom resource delete failed
  src/control-plane/backend/insert-admin-user.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#370 fix: DDB ExpressionAttributeValues empty error
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#373 fix: ddb marshall options
  src/control-plane/backend/lambda/api/common/dynamodb-client.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/store.test.ts
  src/control-plane/backend/lambda/batch-insert-ddb/index.ts
Labels: bug, p1

#375 fix: empty embedding QuickSight iframe
  frontend/package.json
  frontend/yarn.lock
Labels: bug
