Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2023-11, with the labels that each got.

#429 fix: use pending state for stacks when creating/updating the pipeline
  frontend/src/components/pipeline/PipelineStatus.tsx
Labels: bug

#440 feat: support Service Catalog AppRegistry
  .github/workflows/build-sub-projects.yml
  .viperlightignore
  src/common/constant.ts
  src/common/parameters.ts
  src/common/stack.ts
  src/common/utils.ts
  src/control-plane/backend/lambda/api/common/constants.ts
  src/control-plane/backend/lambda/api/common/types.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/utils.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
  src/control-plane/backend/stack-action-state-machine-construct.ts
  src/data-analytics-redshift-stack.ts
  src/data-modeling-athena-stack.ts
  src/data-pipeline-stack.ts
  src/data-reporting-quicksight-stack.ts
  src/ingestion-server-stack.ts
  src/kafka-s3-connector-stack.ts
  src/metrics-stack.ts
  src/service-catalog-appregistry-stack.ts
  test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
  test/analytics/modeling-on-athena/data-modeliing-athena-stack.test.ts
  test/control-plane/click-stream-api.test.ts
  test/data-pipeline/data-pipeline-stack.test.ts
  test/ingestion-server/kafka-s3-connector/kafka-s3-connector-stack.test.ts
  test/ingestion-server/server/ingestion-server-stack.test.ts
  test/metrics/metrics-stack.test.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: feature-request

#452 fix: ignore create role for quicksight embedding in china regions
  src/control-plane/backend/click-stream-api.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#456 fix: dashboard list filter by project and app id
  src/control-plane/backend/lambda/api/service/project.ts
  src/control-plane/backend/lambda/api/store/click-stream-store.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
Labels: bug

#460 fix: miss permission for ec2 DescribeNatGateways
  src/control-plane/backend/click-stream-api.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#469 fix: reporting stack miss parameter
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: bug

#471 fix: vpce is not a service endpoint required for our solution
  src/control-plane/backend/lambda/api/common/constants.ts
  src/control-plane/backend/lambda/api/common/stack-params-valid.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#489 chore: improve explorative api validation
  src/control-plane/backend/lambda/api/router/reporting.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: security

#503 fix: QuickSight subscription check error when creating/updating reporting
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#511 chore: Correlate API Gateway request ID with Lambda request ID
  src/control-plane/backend/lambda/api/common/constants.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/index.ts
  src/control-plane/backend/lambda/api/middle-ware/inject-context.ts
  src/control-plane/backend/layer/lambda-web-adapter/layer.ts
Labels: security

#512 fix: delete analysis while delete dashboard
  src/control-plane/backend/lambda/api/service/project.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
  src/control-plane/backend/lambda/api/test/api/project.test.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: bug

#509 fix: warmup response 4xx for invalidated inputs
  frontend/src/apis/analytics.ts
  frontend/src/pages/analytics/analytics-utils.ts
  frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
  frontend/src/types/analytics.d.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: security

#524 fix: wrong class name of GTMServerDataTransformer
  src/control-plane/backend/config/dictionary.json
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/plugin.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: bug

#525 fix: user settings miss attributes in ddb
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/service/user.ts
  src/control-plane/backend/lambda/api/test/api/user.test.ts
Labels: bug

#532 fix: migration sql error
  src/analytics/private/sqls/redshift/sp-migrate-ods-events-1.0-to-1.1.sql
  src/cloudfront-control-plane-stack.ts
  src/control-plane/cloudfront-s3-portal.ts
Labels: bug

#539 fix: wrong time range when dates cross days
  src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
  test/data-pipeline/emr-job-submitter.test.ts
Labels: bug

#540 fix: set warm pool default value to 0 when pipeline update
  frontend/src/ts/utils.ts
Labels: bug

#541 fix: step function execution error when retry
  src/analytics/private/load-ods-data-workflow.ts
  test/analytics/analytics-on-redshift/load-data-workflow/load-data-stepfuncs.json
  test/analytics/analytics-on-redshift/load-data-workflow/load-data-stepfuncs.test.ts
Labels: bug

#542 fix: update pipeline from v1.0 version
  src/control-plane/backend/lambda/api/common/types.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/store.test.ts
Labels: bug

#548 fix: check user email when create/update user
  src/control-plane/backend/lambda/api/router/user.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/user.test.ts
Labels: security

#552 fix: upgrade pipeline with empty reporting object
  src/control-plane/backend/lambda/api/common/stack-params-valid.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#550 chore: return 403 when authentication exception
  src/control-plane/auth/index.ts
  src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
  test/control-plane/lambda/auth.test.ts
Labels: security

#576 fix: add region info in CloudFront resources name to avoid rare conflicts
  src/cloudfront-control-plane-stack.ts
  src/common/stack.ts
  test/control-plane/cloudfront-control-plane-stack.test.ts
Labels: bug

#568 docs: add identity management page
  docs/en/identity-mgmt.md
  docs/mkdocs.en.yml
  docs/mkdocs.zh.yml
  docs/zh/identity-mgmt.md
Labels: documentation

#517 docs: add upgrade page
  docs/en/pipeline-mgmt/pipe-mgmt.md
  docs/en/upgrade.md
  docs/mkdocs.en.yml
  docs/mkdocs.zh.yml
  docs/zh/pipeline-mgmt/pipe-mgmt.md
  docs/zh/upgrade.md
Labels: documentation

#580 fix: retention with join column
  frontend/public/locales/en-US/analytics.json
  frontend/public/locales/zh-CN/analytics.json
  frontend/src/pages/analytics/analytics-utils.ts
  frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
  frontend/src/types/analytics.d.ts
  src/control-plane/backend/config/dictionary.json
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
  src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
Labels: bug

#595 chore: request projectId validate
  src/control-plane/backend/lambda/api/common/request-valid.ts
  src/control-plane/backend/lambda/api/router/metadata.ts
  src/control-plane/backend/lambda/api/router/reporting.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: security

#598 chore: catch invalid uri error
  src/control-plane/backend/lambda/api/middle-ware/error-handler.ts
  src/control-plane/backend/lambda/api/test/api/app.test.ts
Labels: security

#600 chore: remove data source ARN and owner principal in create dashboard api
  frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
  frontend/src/types/analytics.d.ts
  src/control-plane/backend/lambda/api/model/project.ts
  src/control-plane/backend/lambda/api/router/project.ts
  src/control-plane/backend/lambda/api/service/project.ts
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
Labels: security

#599 chore: validate user name length
  src/control-plane/backend/lambda/api/router/user.ts
  src/control-plane/backend/lambda/api/test/api/user.test.ts
Labels: security

#399 docs: add flutter sdk
  README.md
  docs/en/sdk-manual/android.md
  docs/en/sdk-manual/flutter.md
  docs/en/sdk-manual/index.md
  docs/en/sdk-manual/web.md
  docs/mkdocs.en.yml
  docs/mkdocs.zh.yml
  docs/zh/sdk-manual/android.md
  docs/zh/sdk-manual/flutter.md
  docs/zh/sdk-manual/index.md
  docs/zh/sdk-manual/swift.md
  docs/zh/sdk-manual/web.md
Labels: documentation

#614 fix: able to delete project when it status is failed
  src/control-plane/backend/lambda/api/service/project.ts
  src/control-plane/backend/lambda/api/test/api/project.test.ts
Labels: bug
