Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2023-08, with the labels that each got.

#113 feat: backend metadata manage api
  src/common/constant.ts
  src/common/utils.ts
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/common/constants.ts
  src/control-plane/backend/lambda/api/common/dynamodb-client.ts
  src/control-plane/backend/lambda/api/common/types.ts
  src/control-plane/backend/lambda/api/index.ts
  src/control-plane/backend/lambda/api/model/metadata.ts
  src/control-plane/backend/lambda/api/router/metadata.ts
  src/control-plane/backend/lambda/api/service/metadata.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/store/metadata-store.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/metadata.test.ts
  test/control-plane/click-stream-api.test.ts
Labels: webconsole-backend

#126 chore: optimize pipeline detail api
  src/control-plane/backend/lambda/api/common/types.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/application.ts
  src/control-plane/backend/lambda/api/service/environment.ts
  src/control-plane/backend/lambda/api/service/metadata.ts
  src/control-plane/backend/lambda/api/service/pipeline.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
Labels: webconsole-backend

#117 docs: add web sdk
  README.md
  docs/en/sdk-manual/android.md
  docs/en/sdk-manual/index.md
  docs/en/sdk-manual/swift.md
  docs/en/sdk-manual/web.md
  docs/mkdocs.en.yml
  docs/mkdocs.zh.yml
  docs/zh/sdk-manual/android.md
  docs/zh/sdk-manual/index.md
  docs/zh/sdk-manual/swift.md
  docs/zh/sdk-manual/web.md
Labels: documentation

#131 chore: polish code of web console backend
  src/common/solution-info.ts
  src/control-plane/auth/authorizer.ts
  src/control-plane/backend/Dockerfile
  src/control-plane/backend/batch-insert-ddb-custom-resource-construct.ts
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/common/stack-params-valid.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/service/pipeline.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/store/aws/acm.ts
  src/control-plane/backend/lambda/api/store/aws/athena.ts
  src/control-plane/backend/lambda/api/store/aws/ec2.ts
  src/control-plane/backend/lambda/api/store/aws/iam.ts
  src/control-plane/backend/lambda/api/store/aws/kafka.ts
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/store/aws/redshift.ts
  src/control-plane/backend/lambda/api/store/aws/route53.ts
  src/control-plane/backend/lambda/api/store/aws/s3.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
  src/control-plane/backend/lambda/sfn-action/index.ts
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  src/control-plane/backend/layer/lambda-web-adapter/Dockerfile
  src/control-plane/backend/stack-action-state-machine-construct.ts
Labels: webconsole-backend

#137 fix: grant api function access to read and write metadata table
  src/alb-control-plane-stack.ts
  src/control-plane/backend/click-stream-api.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#147 fix: add UpdateRoleDescription permission for upgrade
  src/control-plane/backend/stack-action-state-machine-construct.ts
  test/control-plane/click-stream-api.test.ts
Labels: bug

#143 feat: funnel analytics preview
  .viperlightignore
  frontend/public/locales/en/analytics.json
  frontend/public/locales/en/common.json
  frontend/public/locales/zh/analytics.json
  frontend/public/locales/zh/common.json
  frontend/src/App.tsx
  frontend/src/apis/analytics.ts
  frontend/src/components/layouts/Header.tsx
  frontend/src/components/layouts/Navigation.tsx
  frontend/src/components/layouts/SwitchSpaceModal.tsx
  frontend/src/pages/analytics/AnalyticsHome.tsx
  frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
  frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx
  frontend/src/pages/analytics/event/AnalyticsEvent.tsx
  frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
  frontend/src/pages/analytics/metadata/event-parameters/MetadataParameterSplitPanel.tsx
  frontend/src/pages/analytics/metadata/event-parameters/MetadataParameters.tsx
  frontend/src/pages/analytics/metadata/events/MetadataEventSplitPanel.tsx
  frontend/src/pages/analytics/metadata/events/MetadataEvents.tsx
  frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributes.tsx
  frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
  frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
  frontend/src/ts/utils.ts
  frontend/src/types/analytics.d.ts
  frontend/src/types/pipeline.d.ts
  src/cloudfront-control-plane-stack.ts
  src/control-plane/backend/Dockerfile
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/common/constants.ts
  src/control-plane/backend/lambda/api/common/types.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
  test/control-plane/click-stream-api.test.ts
  test/control-plane/cloudfront-control-plane-stack.test.ts
Labels: webconsole-backend, webconsole-frontend

#148 fix: create schemas custom resource response attribute name error
  src/analytics/private/app-schema.ts
  src/common/constant.ts
Labels: bug

#153 feat: Dashboards management
  .viperlightignore
  frontend/package.json
  frontend/public/locales/en/analytics.json
  frontend/public/locales/en/common.json
  frontend/public/locales/zh/analytics.json
  frontend/public/locales/zh/common.json
  frontend/src/apis/analytics.ts
  frontend/src/pages/analytics/comps/DashboardHeader.tsx
  frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
  frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
  frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx
  frontend/src/types/analytics.d.ts
  frontend/yarn.lock
  src/control-plane/backend/lambda/api/model/project.ts
  src/control-plane/backend/lambda/api/router/project.ts
  src/control-plane/backend/lambda/api/service/project.ts
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/store/click-stream-store.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/env-bucket-policy.test.ts
Labels: webconsole-backend, webconsole-frontend

#163 fix: create Athena stack when pipeline disable redshift
  frontend/src/pages/common/Tags.tsx
  frontend/src/pages/pipelines/create/CreatePipeline.tsx
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: Cherry Pick

#158 fix: cors not working when specifying specific domain(s)
  frontend/public/locales/en/pipeline.json
  frontend/public/locales/zh/pipeline.json
  frontend/src/pages/pipelines/create/steps/ConfigIngestion.tsx
  src/common/constant.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/utils.test.ts
  src/ingestion-server/server/images/nginx/config/docker-entrypoint.sh
  src/ingestion-server/server/images/nginx/config/nginx.conf
  test/ingestion-server/server/ingestion-server-stack.test.ts
Labels: bug

#176 fix: cors not working when specifying specific domain(s)
  frontend/public/locales/en/pipeline.json
  frontend/public/locales/zh/pipeline.json
  frontend/src/pages/pipelines/create/steps/ConfigIngestion.tsx
  src/common/constant.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/utils.test.ts
  src/ingestion-server/server/images/nginx/config/docker-entrypoint.sh
  src/ingestion-server/server/images/nginx/config/nginx.conf
  test/ingestion-server/server/ingestion-server-stack.test.ts
Labels: Cherry Pick
