Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2023-12, with the labels that each got.

#629 chore: email length limit
  src/common/constant.ts
  src/control-plane/backend/lambda/api/common/request-valid.ts
  src/control-plane/backend/lambda/api/router/user.ts
  src/control-plane/backend/lambda/api/test/api/utils.test.ts
  src/metrics-stack.ts
  test/metrics/metrics-stack.test.ts
Labels: security

#639 fix: disallow to delete system user that created by solution
  src/control-plane/backend/lambda/api/service/user.ts
  src/control-plane/backend/lambda/api/test/api/user.test.ts
Labels: bug

#648 fix: check XSS in update user api
  src/control-plane/backend/lambda/api/router/user.ts
  src/control-plane/backend/lambda/api/test/api/user.test.ts
Labels: security

#651 chore: limit the input length of name and description
  src/control-plane/backend/lambda/api/common/request-valid.ts
  src/control-plane/backend/lambda/api/router/metadata.ts
  src/control-plane/backend/lambda/api/router/project.ts
  src/control-plane/backend/lambda/api/service/metadata.ts
  src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
  src/control-plane/backend/lambda/api/test/api/metadata.test.ts
  src/control-plane/backend/lambda/api/test/api/user.test.ts
Labels: security

#654 fix: able to delete project whose status is warning
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/service/project.ts
  src/control-plane/backend/lambda/api/test/api/project.test.ts
Labels: bug

#671 fix: error jars parameters when edit v1.0 pipeline
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: bug

#696 fix: CloudFront resource name with region suffix
  src/control-plane/cloudfront-s3-portal.ts
  test/control-plane/cloudfront-s3-portal.test.ts
Labels: bug

#699 fix: return pipeline details when execution no found
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#704 fix: invalidation of event relation ship button
  frontend/src/components/eventselect/AnalyticsType.ts
  frontend/src/components/eventselect/reducer/analyticsEventSelectReducer.ts
  frontend/src/pages/analytics/path/AnalyticsPath.tsx
Labels: bug

#710 chore: check existence of the s3 bucket
  frontend/public/locales/en-US/pipeline.json
  frontend/public/locales/zh-CN/pipeline.json
  frontend/src/pages/pipelines/create/CreatePipeline.tsx
  frontend/src/pages/pipelines/create/steps/BasicInformation.tsx
  frontend/src/ts/init.ts
  frontend/src/types/pipeline.d.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/store/aws/s3.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: Cherry Pick

#711 fix: return pipeline details when execution no found
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: Cherry Pick

#715 fix: support updating domain, endpoint path and auth secret of ingestion
  src/ingestion-server/custom-resource/update-alb-rules/index.ts
  test/ingestion-server/custom-resource/update-alb-rules.test.ts
Labels: Cherry Pick

#713 docs: add items in Clickstream SDKs manual
  docs/en/sdk-manual/android.md
  docs/en/sdk-manual/flutter.md
  docs/en/sdk-manual/swift.md
  docs/en/sdk-manual/web.md
  docs/zh/sdk-manual/android.md
  docs/zh/sdk-manual/flutter.md
  docs/zh/sdk-manual/swift.md
  docs/zh/sdk-manual/web.md
Labels: documentation

#717 docs: update table name in http api
  docs/en/sdk-manual/http-api.md
  docs/zh/sdk-manual/http-api.md
Labels: documentation
