Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2024-04, with the labels that each got.

#1017 chore: fix example data generator user first touch timestamp
  examples/standalone-data-generator/application/shopping/ShoppingApp.py
Labels: bug

#1015 docs: add react native SDK manual
  README.md
  docs/en/sdk-manual/android.md
  docs/en/sdk-manual/flutter.md
  docs/en/sdk-manual/index.md
  docs/en/sdk-manual/react-native.md
  docs/en/sdk-manual/swift.md
  docs/en/sdk-manual/web.md
  docs/en/sdk-manual/wechat.md
  docs/mkdocs.en.yml
  docs/mkdocs.zh.yml
  docs/zh/sdk-manual/android.md
  docs/zh/sdk-manual/flutter.md
  docs/zh/sdk-manual/index.md
  docs/zh/sdk-manual/react-native.md
Labels: documentation

#1028 fix: analytics dropdown component style issue
  frontend/src/index.scss
Labels: Cherry Pick

#1031 docs: add record screen views for react navigation in SDK manual
  docs/en/sdk-manual/android.md
  docs/en/sdk-manual/react-native.md
  docs/en/sdk-manual/swift.md
  docs/en/sdk-manual/web.md
  docs/zh/sdk-manual/android.md
  docs/zh/sdk-manual/react-native.md
  docs/zh/sdk-manual/swift.md
  docs/zh/sdk-manual/web.md
Labels: documentation

#1038 chore: handle unsupported UTF8 data
  src/analytics/lambdas/load-data-workflow/load-manifest-to-redshift.ts
Labels: Cherry Pick

#1033 docs: add record screen view events in flutter SDK manual
  docs/en/sdk-manual/flutter.md
  docs/zh/sdk-manual/flutter.md
  docs/zh/sdk-manual/react-native.md
Labels: documentation

#1048 fix: error execution input when app update
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/application.test.ts
Labels: bug

#1050 chore(example): fix data generator user attributes shallow copy issue
  examples/standalone-data-generator/application/shopping/ShoppingApp.py
Labels: bug

#1062 docs: add traffic source in SDK manual
  docs/en/sdk-manual/android.md
  docs/en/sdk-manual/flutter.md
  docs/en/sdk-manual/react-native.md
  docs/en/sdk-manual/swift.md
  docs/en/sdk-manual/web.md
  docs/zh/sdk-manual/android.md
  docs/zh/sdk-manual/flutter.md
  docs/zh/sdk-manual/react-native.md
  docs/zh/sdk-manual/swift.md
  docs/zh/sdk-manual/web.md
Labels: documentation

#1065 fix: write db error and timezone parameter overwrite when updating a project
  frontend/src/pages/application/create/comp/RegisterApp.tsx
  frontend/src/ts/const.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/application.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
  src/control-plane/backend/lambda/api/test/api/application.test.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#1067 fix: stack information callback error when stack had been deleted
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  test/control-plane/lambda/sfn-workflow.test.ts
Labels: bug

#1063 docs: add React Native SDK link in project readme
  README.md
Labels: documentation

#1070 fix: pipeline execution callback bucket error
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  test/control-plane/lambda/sfn-workflow.test.ts
Labels: bug

#1073 fix: version range of ClickstreamMetadataDdbArn
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
Labels: bug

#1074 fix: use console region as s3 region in workflow
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  test/control-plane/lambda/sfn-workflow.test.ts
Labels: bug

#1098 chore: grant the role with tagging glue resources permission
  src/data-pipeline/utils/utils-role.ts
  test/data-pipeline/data-pipeline-stack.test.ts
Labels: Cherry Pick

#1100 chore: stored procedures to migrate event to v2
  docs/en/upgrade.md
  docs/zh/upgrade.md
  src/analytics/private/sql-def.ts
  src/analytics/private/sqls/redshift/fn-combine-json-list.sql
  src/analytics/private/sqls/redshift/fn-parse-utm-from-url.sql
  src/analytics/private/sqls/redshift/fn-rm-object-props.sql
  src/analytics/private/sqls/redshift/fn-transform-event-custom-props.sql
  src/analytics/private/sqls/redshift/fn-transform-user-custom-props.sql
  src/analytics/private/sqls/redshift/sp-migrate-data-to-v2.sql
  src/analytics/private/sqls/redshift/sp-migrate-event-to-v2.sql
  src/analytics/private/sqls/redshift/sp-migrate-item-to-v2.sql
  src/analytics/private/sqls/redshift/sp-migrate-session-to-v2.sql
  src/analytics/private/sqls/redshift/sp-migrate-user-to-v2.sql
Labels: Cherry Pick

#1106 fix: stack create error when pre stack output is null
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  test/control-plane/lambda/sfn-workflow.test.ts
Labels: bug

#1109 fix: stack create error when pre stack output is null
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  test/control-plane/lambda/sfn-workflow.test.ts
Labels: Cherry Pick

#1110 fix: limit sql to less than 100K
  src/analytics/private/sqls/redshift/fn-parse-utm-from-url.sql
Labels: Cherry Pick

#1113 chore: builtin dashboard performance improvement
  frontend/public/locales/en-US/common.json
  frontend/public/locales/zh-CN/common.json
  frontend/src/pages/analytics/analytics-utils.ts
  frontend/src/pages/analytics/comps/AttributeGroup.tsx
  frontend/src/pages/analytics/event/AnalyticsEvent.tsx
  frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
  frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
  frontend/src/types/analytics.d.ts
  src/analytics/private/sql-def.ts
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_intra_day.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_intra_day_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_intra_day_user_mv.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_view_v3.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_lifecycle_view_v2.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_lifecycle_weekly_view_v3.sql
  src/base-lib/src/constant/dashboard.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-check.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
  src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-bar-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-line-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/retention-bar-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/retention-line-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/retention-pivot-table-chart-multiple.json
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
  src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
  src/reporting/private/dashboard.ts
  src/reporting/private/dataset-col-def.ts
  src/reporting/private/template-def.json
  src/reporting/quicksight-custom-resource.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1118 fix: pipeline create failed with role prefix
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
  src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts
Labels: bug

#1120 fix: wrong traffic source configuration rule s3 path
  src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
  src/data-pipeline/utils/utils-lambda.ts
  test/data-pipeline/emr-job-submitter.test.ts
Labels: bug

#1123 chore: append is_first_day_event in metadata
  frontend/src/pages/analytics/analytics-utils.ts
  frontend/src/pages/analytics/comps/AttributeGroup.tsx
  frontend/src/ts/utils.ts
  src/control-plane/backend/lambda/api/service/display.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
  src/control-plane/backend/lambda/api/test/api/metadata-v3.test.ts
  src/control-plane/backend/lambda/api/test/api/metadata.test.ts
Labels: Cherry Pick

#1124 fix: pipeline create failed with role prefix
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
  src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts
Labels: Cherry Pick

#1127 chore: update intra-day user and retention visuals
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_base_view.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_view_v3.sql
  src/reporting/private/template-def.json
  src/reporting/quicksight-custom-resource.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1114 fix: incorrectly enable reporting in service unavailable region
  .projenrc.js
  frontend/.projen/deps.json
  frontend/.projen/tasks.json
  frontend/package.json
  frontend/src/ts/utils.ts
  frontend/test/msk-redshift.test.tsx
  pnpm-lock.yaml
Labels: bug

#1128 fix: type error in user device sp
  src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql
Labels: Cherry Pick

#1129 chore: check app timezone when upgrade
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/service/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: Cherry Pick

#1131 chore: use existing physicalId of batch insert lambda to recognize as an updateable resource
  src/control-plane/backend/lambda/batch-insert-ddb/index.ts
  test/control-plane/lambda/batch-insert-ddb.test.ts
Labels: Cherry Pick

#1133 fix: EMR job submitter lambda role for config rule files
  src/data-pipeline/utils/utils-lambda.ts
  test/data-pipeline/data-pipeline-stack.test.ts
Labels: bug

#1140 fix: truncate rule and topic name
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#1147 fix: lambda put s3 role permissions
  src/data-pipeline/utils/utils-lambda.ts
  test/data-pipeline/data-pipeline-stack.test.ts
Labels: bug

#1146 fix: retry all stacks when delete failed
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: bug

#1151 fix: truncate rule and topic name
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: Cherry Pick

#1152 chore: path analysis specify nodes
  frontend/public/locales/en-US/analytics.json
  frontend/public/locales/zh-CN/analytics.json
  frontend/src/components/eventselect/reducer/analyticsEventSelectReducer.ts
  frontend/src/pages/analytics/path/AnalyticsPath.tsx
Labels: Cherry Pick

#1153 fix: no plugin display in detail page in some cases
  frontend/src/pages/pipelines/detail/comps/Processing.tsx
  frontend/src/pages/plugins/comps/PluginTable.tsx
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
Labels: Cherry Pick

#1154 fix: clean state when close create user modal
  frontend/src/pages/user/CreateUser.tsx
Labels: bug

#1168 fix: catch exceptions since CFN SDK operations are not idempotent
  src/control-plane/backend/lambda/sfn-action/index.ts
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  test/control-plane/lambda/sfn-action.test.ts
Labels: bug

#1172 fix: retry all stacks when delete failed
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: Cherry Pick

#1173 fix: clean state when close create user modal
  frontend/src/pages/user/CreateUser.tsx
Labels: Cherry Pick

#1174 fix: catch exceptions since CFN SDK operations are not idempotent
  src/control-plane/backend/lambda/sfn-action/index.ts
  src/control-plane/backend/lambda/sfn-workflow/index.ts
  test/control-plane/lambda/sfn-action.test.ts
Labels: Cherry Pick

#1175 chore: compensation all stacks status when execution is final state
  src/control-plane/backend/event-bus-construct.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/store/aws/cloudformation.ts
  src/control-plane/backend/lambda/listen-stack-status/index.ts
  src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts
  src/control-plane/backend/lambda/listen-state-status/index.ts
  src/control-plane/backend/stack-action-state-machine-construct.ts
  test/control-plane/click-stream-api.test.ts
  test/control-plane/lambda/listen-state-status.test.ts
  test/jestEnv.js
Labels: Cherry Pick

#1179 chore: footer add control plane stack link
  frontend/src/components/layouts/Footer.tsx
Labels: Cherry Pick

#1180 chore: add version to metadata
  src/analytics/lambdas/scan-metadata-workflow/store-metadata-into-ddb.ts
  src/base-lib/src/constant/constant.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
  src/control-plane/backend/lambda/api/test/api/metadata-mock.ts
  src/control-plane/backend/lambda/api/test/api/metadata-v3.test.ts
  src/control-plane/backend/lambda/api/test/api/metadata.test.ts
  test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/store-metadata-into-ddb.test.ts
Labels: Cherry Pick

#1189 chore: UI optimization
  frontend/public/locales/en-US/application.json
  frontend/public/locales/zh-CN/application.json
  frontend/src/index.scss
  frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
  frontend/src/pages/application/detail/comp/ConfigReactNativeSDK.tsx
  frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
  frontend/src/ts/guideConst.ts
Labels: Cherry Pick

#1195 chore: delete DataFreshnessInHour for data modeling stack
  src/analytics/parameter.ts
  src/common/parameters.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
Labels: Cherry Pick

#1199 chore: render category in sql
  .projenrc.js
  pnpm-lock.yaml
  src/analytics/lambdas/custom-resource/create-schemas.ts
  src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
  src/analytics/private/model.ts
  src/analytics/private/sqls/redshift/event-v2.sql
  src/base-lib/.projen/deps.json
  src/base-lib/.projen/tasks.json
  src/base-lib/package.json
  src/base-lib/src/common/utils.ts
  src/base-lib/src/constant/constant.ts
  src/base-lib/src/constant/explore-types.ts
  src/control-plane/backend/lambda/api/common/utils.ts
Labels: Cherry Pick
