Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2024-07, with the labels that each got.

#1508 fix: upgrade esbuild to resolve lambda runtime package not found error
  package.json
  pnpm-lock.yaml
Labels: bug

#1514 docs: revised the SDK integration steps in the getting started section
  docs/en/getting-started/3.integrate-sdk.md
  docs/zh/getting-started/3.integrate-sdk.md
Labels: documentation

#1517 docs: revised the SDK integration steps in the getting started section
  docs/en/getting-started/3.integrate-sdk.md
  docs/zh/getting-started/3.integrate-sdk.md
Labels: documentation

#1521 docs: fix toc of integrate sdk in getting started
  docs/en/getting-started/3.integrate-sdk.md
  docs/zh/getting-started/3.integrate-sdk.md
Labels: documentation

#1522 docs: update the toc of integrate sdk
  docs/en/getting-started/3.integrate-sdk.md
  docs/zh/getting-started/3.integrate-sdk.md
Labels: documentation

#1526 fix: realtime embedding error
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/realtime.test.ts
Labels: bug

#1542 fix: stream name to lower case
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/realtime.test.ts
Labels: bug

#1544 fix: error loading in project details page
  frontend/src/pages/projects/detail/ProjectDetail.tsx
Labels: bug

#1545 fix: pipeline pending status
  frontend/src/pages/pipelines/detail/PipelineDetail.tsx
Labels: bug

#1550 fix: change the download url of kafka s3 connector plugin
  src/kafka-s3-connector-stack.ts
  test/ingestion-server/kafka-s3-connector/kafka-s3-connector-stack.test.ts
Labels: Cherry Pick

#1549 fix: endpoint service name miss match in China region
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#1553 fix: dashboard create failed when reporting user arn is empty
  src/control-plane/backend/lambda/api/store/aws/quicksight.ts
  src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
Labels: bug

#1546 fix: grant incorrect permissions for different roles
  frontend/public/locales/en-US/analytics.json
  frontend/public/locales/zh-CN/analytics.json
  frontend/src/AppRouter.tsx
  frontend/src/components/layouts/AnalyticsNavigation.tsx
  frontend/src/pages/analytics/segments/UserSegments.tsx
  src/control-plane/backend/lambda/api/middle-ware/auth-role.ts
  src/control-plane/backend/lambda/api/test/api/auth.test.ts
Labels: bug

#1555 fix: revert delete built-in tags and error message when deleting built-in tags
  frontend/src/pages/common/Tags.tsx
  frontend/src/pages/pipelines/create/CreatePipeline.tsx
  src/base-lib/src/constant/constant.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug
