Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2024-06, with the labels that each got.

#1402 docs: added error code when attribute value is infinite in swift SDK manual
  docs/en/sdk-manual/swift.md
  docs/zh/sdk-manual/swift.md
Labels: documentation

#1403 fix: mitigate the duplicated sessions
  src/analytics/private/sqls/redshift/sp-merge-session.sql
Labels: Cherry Pick

#1405 chore: EMR cost optimization for small data
  src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV3.java
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseThirdPartyTransformer.java
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseTransformerV3.java
  test/data-pipeline/emr-job-submitter.test.ts
Labels: Cherry Pick

#1409 chore: polish emr job submitting
  src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
Labels: Cherry Pick

#1414 fix: use caffeine cache in ETL
  src/data-pipeline/etl-common/build.gradle
  src/data-pipeline/etl-common/gradle.properties
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Cache.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/UAEnrichHelper.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/CacheTest.java
  src/data-pipeline/spark-etl/build.gradle
  src/data-pipeline/spark-etl/gradle.properties
Labels: Cherry Pick

#1420 chore: use stack parameter previous value
  src/control-plane/backend/lambda/sfn-action/index.ts
  test/control-plane/lambda/sfn-action.test.ts
Labels: Cherry Pick

#1422 fix: unable to parse custom traffic source with illegal characters
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Util.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/util/UtilTest.java
Labels: Cherry Pick

#1429 fix: upgrade pipeline with deleted paramters
  src/control-plane/backend/lambda/sfn-action/index.ts
  test/control-plane/lambda/sfn-action.test.ts
Labels: bug

#1431 fix: upgrade pipeline with deleted paramters
  src/control-plane/backend/lambda/sfn-action/index.ts
  test/control-plane/lambda/sfn-action.test.ts
Labels: Cherry Pick

#1428 fix: no authentication required for health check
  src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
  src/control-plane/backend/lambda/api/test/api/auth.test.ts
Labels: bug

#1434 fix: medium of traffic source
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
Labels: Cherry Pick

#1432 fix: Explorations are incorrectly disabled
  frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
Labels: bug

#1436 fix: retry upgrading failure does not work
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: bug

#1437 fix: editing pipeline causes illegal version string error
  frontend/src/ts/utils.ts
Labels: bug

#1439 fix: disable switch of app streaming without the streaming module
  frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
Labels: bug

#1444 fix: incorrect active user count in acquisition sheet
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
Labels: Cherry Pick

#1442 chore: add bracket to inferred medium
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/ts/rule/ChannelRuleEvaluatorInput.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_web.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_user.json
  src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/gtm/GTMServerDataTransformerV2Test.java
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_items_data_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_no_js_client_id_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_single_data_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_user_v2.json
Labels: Cherry Pick

#1451 fix: EMR server-less application upgrade
  src/data-pipeline/utils/custom-resource.ts
  test/data-pipeline/data-pipeline-stack.test.ts
Labels: Cherry Pick

#1452 fix: project edit error and allow DevMode change
  frontend/src/pages/projects/comps/SplitPanel.tsx
  src/control-plane/backend/lambda/api/model/stacks.ts
Labels: bug

#1453 fix: stream enable and disable button
  frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
Labels: bug

#1446 docs: add example duration and cost of post-upgrade steps
  docs/en/upgrade.md
  docs/zh/upgrade.md
Labels: documentation

#1455 docs: update flutter and react native SDK version
  docs/en/sdk-manual/flutter.md
  docs/en/sdk-manual/react-native.md
  docs/zh/sdk-manual/flutter.md
  docs/zh/sdk-manual/react-native.md
Labels: documentation

#1448 fix: url parse illegal char in path
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/BaseEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ClickstreamEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Util.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/gtm/GTMEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/sensors/SensorsEventParser.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_items_data_v2.json
Labels: Cherry Pick

#1456 chore: optimize ODS data load
  src/analytics/private/sqls/redshift/sp-merge-event-v2.sql
  src/analytics/private/sqls/redshift/sp-merge-item-v2.sql
  src/analytics/private/sqls/redshift/sp-merge-session.sql
  src/analytics/private/sqls/redshift/sp-merge-user-v2.sql
Labels: Cherry Pick

#1457 chore: use refresh start time to refresh base view
  src/analytics/lambdas/refresh-materialized-views-workflow/refresh-basic-view.ts
  src/analytics/private/refresh-materialized-views-workflow.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/refresh-basic-view.test.ts
Labels: Cherry Pick

#1461 fix: traffic source cache
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/BaseEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/ts/rule/ChannelListEvaluator.java
Labels: Cherry Pick

#1463 chore: funnel visual performance improvement
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
  src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-funnel-chart.json
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
Labels: Cherry Pick

#1470 docs: merge SDK version updates and post-upgrade cost example documentation
  docs/en/sdk-manual/flutter.md
  docs/en/sdk-manual/react-native.md
  docs/en/upgrade.md
  docs/zh/sdk-manual/flutter.md
  docs/zh/sdk-manual/react-native.md
  docs/zh/upgrade.md
Labels: documentation

#1473 fix: issues of real-time UI
  frontend/public/locales/en-US/pipeline.json
  frontend/public/locales/zh-CN/pipeline.json
  frontend/src/components/common/ExtendIcon.tsx
  frontend/src/components/layouts/AnalyticsNavigation.tsx
  frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
  frontend/src/pages/pipelines/detail/comps/Ingestion.tsx
  frontend/src/pages/pipelines/detail/comps/Processing.tsx
  frontend/src/types/pipeline.d.ts
  src/control-plane/backend/lambda/api/common/types.ts
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#1487 fix: null point exception in event parser
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/BaseEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ClickstreamEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Util.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/ts/rule/CategoryListEvaluator.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/ClickstreamEventParserTest.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/util/UtilTest.java
  src/data-pipeline/etl-common/src/test/resources/empty_latest_referrer.json
  src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/ClickstreamDataConverterV3Test.java
  src/data-pipeline/spark-etl/src/test/resources/empty_latest_referrer.json
Labels: bug

#1482 docs: fix layout and region support up to date
  docs/en/pipeline-mgmt/basic.md
  docs/en/pipeline-mgmt/ingestion/configure-ingestion-endpoint.md
  docs/en/plan-deployment/regions.md
  docs/zh/pipeline-mgmt/ingestion/configure-ingestion-endpoint.md
  docs/zh/plan-deployment/regions.md
Labels: Cherry Pick
