Repository awslabs/clickstream-analytics-on-aws, pull requests merged in 2024-05, with the labels that each got.

#1204 fix: improve engagement time accuracy in edge case
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_view_v3.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_lifecycle_weekly_view_v3.sql
  src/reporting/private/dataset-col-def.ts
  src/reporting/private/template-def-spice.json
  src/reporting/private/template-def.json
  src/reporting/quicksight-custom-resource.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1211 chore: edit style of group select component
  frontend/src/pages/analytics/comps/AttributeGroup.tsx
Labels: Cherry Pick

#1212 fix: show pattern only source category is Search
  frontend/src/pages/analytics/traffic-source/modal/SourceCategoryModal.tsx
Labels: Cherry Pick

#1217 chore: increase timeout in step function lambda for CFN SDK
  src/base-lib/src/common/sdk-client-config.ts
  src/control-plane/backend/lambda/sfn-action/index.ts
  src/control-plane/backend/lambda/sfn-workflow/index.ts
Labels: Cherry Pick

#1216 chore: replace the SFN deprecated fields
  src/analytics/private/load-ods-data-workflow.ts
  src/analytics/private/refresh-materialized-views-workflow.ts
  src/analytics/private/scan-metadata-workflow.ts
  src/analytics/private/sql-execution-workflow.ts
  test/analytics/analytics-on-redshift/workflow/load-data-sub-stepfuncs.json
  test/analytics/analytics-on-redshift/workflow/sql-execution-sfn.json
Labels: Cherry Pick

#1215 fix: ingest time loses when transforming the raw data
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ClickstreamEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/gtm/GTMEventParser.java
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_disable_time_shift.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_v2.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_web.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_time_shift.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_zip_event_v2.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/etl_runner_v3_event1.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_event.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_event_max_len2.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_gzip_event.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_traffic_source_event.json
  src/data-pipeline/spark-etl/src/test/resources/expected/test_convert_data_v3.json
Labels: Cherry Pick

#1220 chore: update base event view for incremental re-computation
  src/analytics/lambdas/custom-resource/create-schemas.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/check-next-refresh-view.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/refresh-basic-view.ts
  src/analytics/private/model.ts
  src/analytics/private/sql-def.ts
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt_mv.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_intra_day_user_mv.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_view_v3.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_base_view.sql
  src/base-lib/src/constant/dashboard.ts
  src/reporting/quicksight-custom-resource.ts
  test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-next-refresh-view.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/refresh-basic-view.test.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1221 chore: clean legacy table
  src/analytics/analytics-on-redshift.ts
  src/analytics/private/constant.ts
  test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
  test/analytics/analytics-on-redshift/lambda/load-data/has-more-job-new.test.ts
  test/analytics/analytics-on-redshift/lambda/load-data/skip-running-workflow.test.ts
Labels: Cherry Pick

#1222 fix: long field value causes scanning workflow failure
  src/analytics/private/sqls/redshift/sp-scan-metadata.sql
Labels: Cherry Pick

#1226 chore: add space between traffic source tables
  frontend/src/pages/analytics/traffic-source/TrafficSourceHome.tsx
Labels: Cherry Pick

#1227 fix: reduce warmup waiting time avoid timeout
  .projenrc.js
  package.json
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: bug

#1228 fix: reduce warmup waiting time avoid timeout
  .projenrc.js
  package.json
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: Cherry Pick

#1231 chore: upgrade project to node v20
  .github/workflows/build-sub-projects.yml
  .github/workflows/build.yml
  .github/workflows/dist-scan.yml
  .github/workflows/upgrade.yml
  .projen/deps.json
  .projenrc.js
  README.md
  buildspec.yml
  frontend/.projen/deps.json
  frontend/README.md
  frontend/package.json
  frontend/src/pages/plugins/create/CreatePlugin.tsx
  package.json
  pnpm-lock.yaml
  src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
  src/analytics/private/utils.ts
  src/cloudfront-control-plane-stack.ts
  src/control-plane/alb-lambda-portal.ts
  src/control-plane/backend/Dockerfile
  src/control-plane/backend/click-stream-api.ts
  src/control-plane/backend/lambda/api/.projen/deps.json
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/package.json
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/layer/lambda-web-adapter/layer.ts
  src/control-plane/frontend/Dockerfile
  src/control-plane/private/constant.ts
  src/data-reporting-quicksight-stack.ts
  src/main.ts
  src/private/function.ts
  test/analytics/analytics-on-redshift/workflow/sql-execution-sfn.test.ts
  test/control-plane/alb-lambda-portal.test.ts
  test/control-plane/click-stream-api.test.ts
  test/control-plane/cloudfront-control-plane-stack.test.ts
  test/control-plane/cloudfront-s3-portal.test.ts
Labels: Cherry Pick

#1235 fix: dashboard issues polish
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_country_new_user_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
  src/reporting/private/template-def-spice.json
  src/reporting/private/template-def.json
Labels: Cherry Pick

#1237 chore: merge data into redshift to avoid duplicate data
  src/analytics/lambdas/load-data-workflow/load-manifest-to-redshift.ts
  src/analytics/private/constant.ts
  src/analytics/private/model.ts
  src/analytics/private/sql-def.ts
  src/analytics/private/sqls/redshift/event-v2.sql
  src/analytics/private/sqls/redshift/sp-merge-event-v2.sql
  src/analytics/private/sqls/redshift/sp-merge-item-v2.sql
  src/analytics/private/sqls/redshift/sp-merge-session.sql
  src/analytics/private/sqls/redshift/sp-merge-user-v2.sql
  test/analytics/analytics-on-redshift/lambda/load-data/load-manifest-to-redshift.test.ts
Labels: Cherry Pick

#1238 chore: clean clickstream log history data
  src/analytics/private/sqls/redshift/sp-clear-expired-data.sql
Labels: Cherry Pick

#1240 fix: add default db param to Reporting stack
  src/data-reporting-quicksight-stack.ts
  src/reporting/parameter.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1250 fix: moment import
  frontend/src/ts/utils.ts
Labels: bug

#1252 fix: ETL cache error when processing huge data
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Cache.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/CacheTest.java
Labels: Cherry Pick

#1254 docs: add Local build spark ETL jar
  README.md
Labels: documentation, Cherry Pick

#1253 docs: add Local build spark ETL jar
  README.md
Labels: documentation

#1244 docs: update web SDK manual
  docs/en/sdk-manual/android.md
  docs/en/sdk-manual/web.md
  docs/zh/sdk-manual/android.md
  docs/zh/sdk-manual/web.md
Labels: documentation

#1248 chore: timezone add UTC offset and stop ping private ALB
  frontend/src/pages/application/create/comp/RegisterApp.tsx
  frontend/src/pages/application/detail/ApplicationDetail.tsx
  frontend/src/pages/pipelines/detail/comps/Ingestion.tsx
  frontend/src/ts/utils.ts
Labels: Cherry Pick

#1258 chore: optimize the refresh views workflow
  src/analytics/analytics-on-redshift.ts
  src/analytics/lambdas/clear-expired-events-workflow/clear-expired-events.ts
  src/analytics/lambdas/custom-resource/create-schemas.ts
  src/analytics/lambdas/load-data-workflow/refresh-views.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/check-next-refresh-sp.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/check-refresh-mv-status.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/check-refresh-sp-status.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/check-start-sp-refresh.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/get-refresh-viewlist.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/refresh-basic-view.ts
  src/analytics/lambdas/refresh-materialized-views-workflow/refresh-sp.ts
  src/analytics/parameter.ts
  src/analytics/private/refresh-materialized-views-workflow.ts
  src/analytics/private/sql-def.ts
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_country_new_user_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_intra_day_user_mv.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_device_crash_rate_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_day_user_view_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_entrance_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_event_name_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_exit_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_detail_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_view_v3.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_base_view.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_dau_wau_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_event_overtime_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_user_new_return_sp.sql
  src/analytics/private/sqls/redshift/session-m-max-view.sql
  src/analytics/private/sqls/redshift/session-m-view.sql
  src/analytics/private/sqls/redshift/sp-clear-expired-data.sql
  src/analytics/private/sqls/redshift/sp-migrate-session-to-v2.sql
  src/analytics/private/sqls/redshift/sp-migrate-user-to-v2.sql
  src/analytics/private/sqls/redshift/sp-scan-metadata.sql
  src/analytics/private/sqls/redshift/user-m-max-view.sql
  src/analytics/private/sqls/redshift/user-m-view-v2.sql
  src/base-lib/src/constant/dashboard.ts
  src/control-plane/backend/lambda/api/model/stacks.ts
  src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
  src/data-analytics-redshift-stack.ts
  test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
  test/analytics/analytics-on-redshift/lambda/clear-expire-events/clear-expire-events.test.ts
  test/analytics/analytics-on-redshift/lambda/load-data/refresh-views.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-next-refresh-sp.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-next-refresh-view.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-refresh-sp-status.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-refresh-view-status.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-start-sp-refresh.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/get-refresh-viewlist.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/refresh-basic-view.test.ts
  test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/refresh-sp.test.ts
  test/jestEnv.js
Labels: Cherry Pick

#1266 chore: ETL filtered data metrics and move migrate sql to separate folder
  src/analytics/private/sql-def.ts
  src/analytics/private/sqls/redshift/migrate/fn-combine-json-list.sql
  src/analytics/private/sqls/redshift/migrate/fn-parse-utm-from-url.sql
  src/analytics/private/sqls/redshift/migrate/fn-rm-object-props.sql
  src/analytics/private/sqls/redshift/migrate/fn-transform-event-custom-props.sql
  src/analytics/private/sqls/redshift/migrate/fn-transform-user-custom-props.sql
  src/analytics/private/sqls/redshift/migrate/sp-migrate-data-to-v2.sql
  src/analytics/private/sqls/redshift/migrate/sp-migrate-event-to-v2.sql
  src/analytics/private/sqls/redshift/migrate/sp-migrate-item-to-v2.sql
  src/analytics/private/sqls/redshift/migrate/sp-migrate-session-to-v2.sql
  src/analytics/private/sqls/redshift/migrate/sp-migrate-user-to-v2.sql
  src/common/model.ts
  src/data-pipeline/lambda/emr-job-state-listener/index.ts
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/UAEnrichmentV2.java
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/Cleaner.java
  src/data-pipeline/utils/metrics.ts
  test/data-pipeline/emr-job-listener.test.ts
Labels: Cherry Pick

#1269 fix: explorative analysis fail to load data when query from shared database
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view_sp.sql
  src/base-lib/src/constant/constant.ts
  src/control-plane/backend/lambda/api/service/attribution.ts
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
  src/data-reporting-quicksight-stack.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1267 fix: add reporting stack with action error
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: bug

#1275 fix: add reporting stack with action error
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/service/stack.ts
  src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow.test.ts
Labels: Cherry Pick

#1276 chore: add RefreshMode parameter
  src/analytics/analytics-on-redshift.ts
  src/analytics/parameter.ts
  src/analytics/private/refresh-materialized-views-workflow.ts
  src/data-analytics-redshift-stack.ts
  test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
Labels: Cherry Pick

#1274 fix: retry when delete failed
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: bug

#1277 fix: retry when delete failed
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: Cherry Pick

#1283 fix: sensors data bot filtered
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/sensors/SensorsEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/sensors/event/Properties.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/sensors/SensorsEventParserTest.java
  src/data-pipeline/etl-common/src/test/resources/sensors-data/expected/test_sensors_data_ingestDataToEvent.json
  src/data-pipeline/etl-common/src/test/resources/sensors-data/expected/test_sensors_data_parseLineToDBRow_event.json
  src/data-pipeline/etl-common/src/test/resources/sensors-data/expected/test_sensors_data_parseLineToDBRow_web_event.json
  src/data-pipeline/etl-common/src/test/resources/sensors-data/sensors-web-ua.json
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/UAEnrichmentV2.java
  src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/ETLRunnerForSensorsDataTest.java
  src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/UAEnrichmentV2Test.java
  src/data-pipeline/spark-etl/src/test/resources/event_v2/transformed_data_ua_null.json
  src/data-pipeline/spark-etl/src/test/resources/sensordata/expected/test_sensors_data_runner.json
  src/data-pipeline/spark-etl/src/test/resources/sensordata/sensors-web-ua.json
Labels: Cherry Pick

#1284 chore: remove deleting clickstream log in scanning metadata to mitigate timeout
  src/analytics/lambdas/scan-metadata-workflow/check-scan-metadata-status.ts
  src/analytics/private/scan-metadata-workflow.ts
  test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/check-scan-metadata-status.test.ts
Labels: Cherry Pick

#1288 fix: ETL job failed alarm is not triggered
  src/data-pipeline/utils/metrics.ts
  test/data-pipeline/data-pipeline-stack.test.ts
Labels: Cherry Pick

#1293 fix: redshift serverless link in GCR
  frontend/src/pages/pipelines/detail/comps/Processing.tsx
  frontend/src/ts/url.ts
Labels: Cherry Pick

#1302 chore: keep users state to 10 years in ETL
  src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
Labels: Cherry Pick

#1303 chore: remove user table operation in clear history data sp
  src/analytics/private/sqls/redshift/sp-clear-expired-data.sql
Labels: Cherry Pick

#1308 chore: adjust EMR initialExecutors for large volume data
  src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
Labels: Cherry Pick

#1312 fix: error tags when update pipeline
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
Labels: bug

#1314 chore: support backslash in authenticationSecretArn
  src/ingestion-server/server/parameter.ts
  test/ingestion-server/server/ingestion-server-stack.test.ts
Labels: Cherry Pick

#1319 fix: error tags when update pipeline
  src/control-plane/backend/lambda/api/model/pipeline.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
  src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
Labels: Cherry Pick

#1317 fix: app_version is null after migrating old data
  src/analytics/private/sqls/redshift/migrate/sp-migrate-event-to-v2.sql
Labels: Cherry Pick

#1318 chore: create clickstream log v2 table
  src/analytics/private/constant.ts
  src/analytics/private/sql-def.ts
  src/analytics/private/sqls/redshift/clickstream-log-v2.sql
  src/analytics/private/sqls/redshift/clickstream-log.sql
  src/analytics/private/sqls/redshift/sp-clickstream-log-non-atomic.sql
  src/analytics/private/sqls/redshift/sp-clickstream-log.sql
Labels: Cherry Pick

#1321 fix: keep url root path
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/BaseEventParser.java
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_web.json
  src/data-pipeline/etl-common/src/test/resources/gtm-server/expected/test_gtm_parseLineToDBRow_event.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_GTM_server_runner_v2_event_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_no_js_client_id_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_session_start1_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_session_start2_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_single_data_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_user_data_user_props_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_user_data_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_brand_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_session_start_v2.json
Labels: Cherry Pick

#1315 fix: sql bugs in device and engagement sheet
  src/analytics/lambdas/custom-resource/create-schemas.ts
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_retention_user_new_return_sp.sql
  src/reporting/private/template-def-spice.json
  src/reporting/private/template-def.json
  src/reporting/quicksight-custom-resource.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1326 fix: app crash rate overtime visual incorrect config
  src/reporting/lambda/custom-resource/quicksight/index.ts
  src/reporting/private/template-def-spice.json
  src/reporting/private/template-def.json
Labels: Cherry Pick

#1327 chore: update ui
  frontend/public/locales/en-US/analytics.json
  frontend/public/locales/en-US/help.json
  frontend/public/locales/zh-CN/analytics.json
  frontend/public/locales/zh-CN/help.json
  frontend/src/hooks/useFetchEvents.ts
  frontend/src/pages/analytics/analytics-utils.ts
  frontend/src/pages/analytics/traffic-source/modal/SourceCategoryModal.tsx
Labels: Cherry Pick

#1323 fix: ETL device_os and install_source are null and traffic source for internal latest referrer
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/BaseEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ClickstreamEventParser.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/ts/rule/CategoryListEvaluator.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ingest/Event.java
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ingest/EventAttributes.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/ClickstreamEventParserTest.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_data.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_disable_time_shift.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_v2.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_web.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_time_shift.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_user.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_zip_event_v2.json
  src/data-pipeline/etl-common/src/test/resources/expected/test_screen_view_engagement_time.json
  src/data-pipeline/etl-common/src/test/resources/one_line.json
  src/data-pipeline/etl-common/src/test/resources/original_data_nozip_upload_time.json
  src/data-pipeline/lambda/emr-job-submitter/traffic_source_category_rule_v1.ts
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV3.java
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseThirdPartyTransformer.java
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseTransformerV3.java
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/etl_runner_v3_event1.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_event.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_event_max_len2.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_gzip_event.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_traffic_source_event.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_traffic_source_user.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_user.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_user2.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_user_first_open.json
  src/data-pipeline/spark-etl/src/test/resources/expected/test_convert_data_v3.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_GTM_server_runner_v2_session.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_no_js_client_id_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_single_data_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_session.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_user_v2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_with_session_v2.json
  src/data-pipeline/spark-etl/src/test/resources/rule_config/app1/traffic_source_category_rule_v1.json
  src/data-pipeline/spark-etl/src/test/resources/ts/traffic_source_category_rule_v0.json
Labels: Cherry Pick

#1329 ci: specify jest workers for stabilizing the build
  .github/workflows/build.yml
  .github/workflows/dist-scan.yml
  .projen/tasks.json
  .projenrc.js
Labels: Cherry Pick

#1334 chore: optimize scan metadata performance
  src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
  src/analytics/lambdas/scan-metadata-workflow/store-metadata-into-ddb.ts
  src/analytics/private/scan-metadata-workflow.ts
  src/analytics/private/sqls/redshift/event-v2.sql
  src/analytics/private/sqls/redshift/session.sql
  src/analytics/private/sqls/redshift/sp-scan-metadata.sql
  src/analytics/private/sqls/redshift/user-v2.sql
  src/control-plane/backend/Dockerfile
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/test/api/metadata-v3.test.ts
  test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/scan-metadata.test.ts
  test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/store-metadata-into-ddb.test.ts
Labels: Cherry Pick

#1337 fix: page view count mismatch
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_detail.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_detail_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_sp.sql
  src/reporting/lambda/custom-resource/quicksight/index.ts
  src/reporting/private/dashboard.ts
  src/reporting/private/template-def-spice.json
  src/reporting/private/template-def.json
  src/reporting/quicksight-custom-resource.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1341 chore: avoid output a lot of small files in ETL
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
Labels: Cherry Pick

#1344 chore: optimize merge performance
  src/analytics/private/sqls/redshift/sp-merge-event-v2.sql
  src/analytics/private/sqls/redshift/sp-merge-item-v2.sql
  src/analytics/private/sqls/redshift/sp-merge-session.sql
  src/analytics/private/sqls/redshift/sp-merge-user-v2.sql
Labels: Cherry Pick

#1345 fix: improve ETL performance
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
Labels: Cherry Pick

#1347 chore: increase timeout to handle large ods file number
  src/analytics/private/load-ods-data-workflow.ts
  test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
Labels: Cherry Pick

#1348 fix: build aarch64 frontend image
  frontend/config/webpack.config.js
  src/alb-control-plane-stack.ts
  src/control-plane/frontend/Dockerfile
Labels: Cherry Pick

#1353 chore: fix frontend local start
  frontend/config/webpack.config.js
Labels: Cherry Pick

#1354 chore: old pipeline allowed to access dashboard
  frontend/public/locales/en-US/analytics.json
  frontend/public/locales/en-US/common.json
  frontend/public/locales/zh-CN/analytics.json
  frontend/src/index.scss
  frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
  frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
  frontend/src/ts/request.ts
  src/control-plane/backend/lambda/api/common/utils.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
Labels: Cherry Pick

#1351 fix: session traffic source
  src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseTransformerV3.java
  src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/TransformerV3Test.java
  src/data-pipeline/spark-etl/src/test/resources/event_v2/event_v2_session_dataset.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/event_v2_session_dataset2.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/test_extract_session_from_event.json
  src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/test_extract_session_from_event2.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_GTM_server_runner_v2_session.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_session.json
  src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_with_session_v2.json
Labels: Cherry Pick

#1355 fix: analysis on event property is not in the expected data format
  src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_country_new_user_sp.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi.sql
  src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
  src/control-plane/backend/lambda/api/service/attribution.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-bar-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-bar-chart.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-line-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-line-chart.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart-multiple.json
  src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart.json
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
  src/reporting/private/template-def-spice.json
  src/reporting/private/template-def.json
  src/reporting/quicksight-custom-resource.ts
  test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
Labels: Cherry Pick

#1362 chore: explore display empty if pipeline short version not latest
  frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
Labels: Cherry Pick

#1364 fix: traffic source medium for internal referrer
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
Labels: Cherry Pick

#1367 chore: pipeline status auto refresh
  frontend/src/components/pipeline/PipelineStatus.tsx
  frontend/src/pages/application/detail/ApplicationDetail.tsx
  frontend/src/pages/pipelines/comps/BasicInfo.tsx
  frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
Labels: Cherry Pick

#1369 chore: add data point count setting
  src/reporting/private/template-def-spice.json
  src/reporting/private/template-def.json
Labels: Cherry Pick

#1370 chore: wait warmup on dashboard detail page
  frontend/src/apis/analytics.ts
  frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx
  src/control-plane/backend/lambda/api/common/sdk-client.ts
  src/control-plane/backend/lambda/api/service/project.ts
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/service/reporting.ts
  src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: Cherry Pick

#1366 docs: add faq for how implementing redshift data sharing
  docs/en/faq.md
  docs/zh/faq.md
Labels: documentation

#1379 fix: support warmup sql in shared database
  src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
  src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Labels: Cherry Pick

#1373 fix: traffic source medium
  src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
  src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
Labels: Cherry Pick

#1378 chore: update doc url
  frontend/src/ts/url.ts
Labels: Cherry Pick

#1376 docs: update data sharing
  docs/en/faq.md
  docs/zh/faq.md
Labels: documentation

#1391 fix: data can't be updated to base view when using custom time range
  src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view_sp.sql
  src/base-lib/src/constant/dashboard.ts
Labels: Cherry Pick

#1390 fix: use incorrect log table in migration sql
  src/analytics/lambdas/clear-expired-events-workflow/check-clear-status.ts
  src/analytics/private/sqls/redshift/migrate/sp-migrate-data-to-v2.sql
  test/analytics/analytics-on-redshift/lambda/clear-expire-events/check-clear-status.test.ts
Labels: Cherry Pick

#1393 fix: attribution analysis failed when specify fixed time range
  src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
  src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
Labels: Cherry Pick
